### ISSUE TITLE
Drupal 9 compatibility plan

### ISSUE THREAD

**Issue by mriffault** [previousnext/drush_cmi_tools#33]
Is there any plan to port the module for Drupal 9?

Thanks

**Comment by larowlan** [comment]
Hi @mriffault - no there's no plan to port this to D9, instead we've been advocating moving to config ignore + config filter as those are on the CMI 2.0 roadmap for core, so it makes sense to align with that direction

**Comment by mriffault** [comment]
Created a PR for Drupal 9 support : #34

**Comment by larowlan** [comment]
https://www.previousnext.com.au/blog/migrate-from-drush-cmi-tools-drupal-9 for docs on migrating
